import React, { useState, useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'

// static assets imported via Vite (will be hashed and served correctly)
import Img1 from '../public/Img1.jpeg'
import Img2 from '../public/Img2.jpeg'
import Img3 from '../public/Img3.jpeg'
import Img4 from '../public/Img4.jpeg'
import Img5 from '../public/Img5.jpeg'

/* ─── Data ─── */
const IMPACT_DATA = [
  { caption: 'Children receive a hot meal at a community distribution drive', location: 'Rajasthan, India' },
  { caption: 'A rescued meal brings joy — one bowl at a time', location: 'Gujarat, India' },
  { caption: 'Families gather for freshly donated bread at a shelter', location: 'Karachi, Pakistan' },
  { caption: 'Every spoonful matters — children fed through NGO partners', location: 'Maharashtra, India' },
  { caption: 'Surplus food reaches those who need it most', location: 'Bihar, India' },
]

// image URLs generated by the bundler; this is the same as the
// old `new URL(...)` approach but works reliably because the files are
// imported rather than referenced from the `src/public` folder.
const IMG_SRCS = [Img1, Img2, Img3, Img4, Img5]

/* Fallback: use the uploaded paths directly if running in dev */
const UPLOADED = [
  '/uploads/WhatsApp_Image_2026-02-28_at_9_39_16_AM.jpeg',
  '/uploads/WhatsApp_Image_2026-02-28_at_9_39_51_AM.jpeg',
  '/uploads/WhatsApp_Image_2026-02-28_at_9_40_13_AM.jpeg',
  '/uploads/WhatsApp_Image_2026-02-28_at_9_41_22_AM.jpeg',
  '/uploads/WhatsApp_Image_2026-02-28_at_9_41_32_AM.jpeg',
]

const STORIES = [
  { quote: "Before FoodBridge, we scrambled every evening wondering if we'd have enough for dinner. Now, hot meals arrive before sunset.", name: 'Sunita Devi', role: 'Mother of three, Rajasthan', emoji: '🌾' },
  { quote: "Our shelter serves 80 children daily. FoodBridge connects us with donors within minutes. It has been life-changing.", name: 'Father Thomas', role: 'Director, Anand Ashram NGO', emoji: '🏠' },
  { quote: "I used to throw away leftover catering after every event. Now those meals feed real families. I feel the difference.", name: 'Rahul Kapoor', role: 'Event Caterer & Donor', emoji: '🍲' },
]

const STATS = [
  { num: '48,200+', label: 'Meals Rescued',   icon: '🍛' },
  { num: '312',     label: 'Active Donors',    icon: '🤝' },
  { num: '89',      label: 'NGO Partners',     icon: '❤️' },
  { num: '97%',     label: 'Utilisation Rate', icon: '📊' },
  { num: '14',      label: 'Cities Covered',   icon: '🌍' },
  { num: '2 min',   label: 'Avg Match Time',   icon: '⚡' },
]

const TIMELINE = [
  { icon: '🌱', label: 'Year One',        title: 'First 1,000 meals rescued',    sub: 'Launched in Bangalore with 12 donor restaurants and 3 NGO partners. Reached 1,000 meals in 6 weeks.' },
  { icon: '📈', label: 'Scaling Up',      title: '10 cities, 50+ NGO partners',  sub: 'Expanded the platform with real-time geo-matching. Average match time dropped to under 2 minutes.' },
  { icon: '❤️', label: 'Community',       title: '48,200+ meals and counting',   sub: 'Today, over 312 active donors and 89 verified NGOs rely on FoodBridge daily.' },
  { icon: '🌍', label: "What's Next",     title: 'Zero food waste, everywhere',  sub: 'Building partnerships with municipal governments and supermarkets to rescue food at scale.' },
]

/* ─── Styles ─── */
const STYLES = `
  @import url('https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,500;0,600;0,700;1,500;1,600&family=Source+Sans+3:wght@300;400;500;600&display=swap');

  *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}

  :root {
    --bg:#0e1a10;--bg2:#152118;--bg3:#1c2e1e;
    --border:rgba(255,255,255,0.13);
    --gold:#d4a843;--gold-dim:rgba(212,168,67,0.15);
    --green:#2d6a4f;--green-lt:#6abf8e;
    --text:#eeeae0;--muted:rgba(238,234,224,0.65);
  }
  html{scroll-behavior:smooth}
  body{background:var(--bg);color:var(--text);font-family:'Source Sans 3',sans-serif;min-height:100vh;overflow-x:hidden}

  body::before{
    content:'';position:fixed;inset:0;pointer-events:none;z-index:9999;opacity:.032;
    background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 512 512' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");
    background-size:200px;animation:grain .4s steps(1) infinite;
  }
  @keyframes grain{0%{background-position:0 0}25%{background-position:-50px 20px}50%{background-position:30px -40px}75%{background-position:-70px 60px}}

  #particle-canvas{position:fixed;inset:0;pointer-events:none;z-index:0;opacity:.2}

  /* NAV */
  .nav{position:fixed;top:0;left:0;right:0;z-index:100;display:flex;align-items:center;justify-content:space-between;padding:20px 60px;background:rgba(13,26,14,.9);backdrop-filter:blur(18px);border-bottom:1px solid var(--border)}
  .nav-logo{font-family:'Lora',serif;font-size:21px;font-weight:600;color:var(--gold);cursor:pointer;letter-spacing:.2px}
  .nav-logo span{color:var(--green-lt);font-style:italic}
  .nav-back{display:flex;align-items:center;gap:8px;font-size:13px;letter-spacing:1px;text-transform:uppercase;color:var(--muted);cursor:pointer;background:none;border:none;font-family:'Source Sans 3',sans-serif;font-weight:500;transition:color .25s}
  .nav-back:hover{color:var(--green-lt)}
  .nav-back-arr{transition:transform .25s}
  .nav-back:hover .nav-back-arr{transform:translateX(-3px)}

  /* PAGE */
  .page{position:relative;z-index:1;padding-top:80px}

  /* HERO */
  .hero{min-height:92vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:100px 40px 80px;position:relative;overflow:hidden}
  .hero::after{content:'';position:absolute;width:900px;height:900px;border-radius:50%;background:radial-gradient(circle,rgba(45,106,79,.13) 0%,transparent 65%);top:50%;left:50%;transform:translate(-50%,-50%);pointer-events:none}
  .hero::before{content:'';position:absolute;top:0;right:0;width:340px;height:340px;background-image:repeating-linear-gradient(-45deg,rgba(212,168,67,.05) 0px,rgba(212,168,67,.05) 1px,transparent 1px,transparent 18px);pointer-events:none}

  .hero-tag{display:inline-flex;align-items:center;gap:10px;border:1px solid rgba(106,191,142,.3);padding:7px 20px;font-size:11px;letter-spacing:3px;text-transform:uppercase;color:var(--green-lt);font-weight:600;background:rgba(106,191,142,.06);margin-bottom:32px;opacity:0;animation:fadeUp .7s .1s forwards;position:relative;z-index:1}
  .tag-dot{width:6px;height:6px;border-radius:50%;background:var(--green-lt);animation:blink 2s infinite}
  @keyframes blink{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.4;transform:scale(.6)}}

  .hero-title{font-family:'Lora',serif;font-size:clamp(52px,9vw,108px);font-weight:700;line-height:.96;letter-spacing:-2px;color:var(--text);margin-bottom:28px;opacity:0;animation:fadeUp .9s .25s forwards;position:relative;z-index:1;text-shadow:0 4px 48px rgba(0,0,0,.6)}
  .hero-title em{font-style:italic;color:var(--gold)}
  .hero-line{width:1px;height:60px;background:linear-gradient(to bottom,var(--green-lt),transparent);margin:0 auto 28px;opacity:0;animation:fadeIn .8s .5s forwards;position:relative;z-index:1}
  .hero-desc{font-size:18px;line-height:1.8;color:var(--muted);max-width:560px;margin:0 auto 52px;opacity:0;animation:fadeUp .9s .55s forwards;position:relative;z-index:1}
  .hero-btns{display:flex;gap:16px;justify-content:center;flex-wrap:wrap;opacity:0;animation:fadeUp .8s .7s forwards;position:relative;z-index:1}

  .btn-primary{background:var(--gold);color:#0d1a0e;border:none;padding:15px 36px;font-family:'Source Sans 3',sans-serif;font-size:14px;font-weight:600;letter-spacing:.5px;cursor:pointer;border-radius:2px;transition:transform .2s,box-shadow .25s;position:relative;overflow:hidden}
  .btn-primary:hover{transform:translateY(-2px);box-shadow:0 12px 36px rgba(212,168,67,.3)}
  .btn-ghost{background:transparent;color:var(--text);border:1px solid rgba(255,255,255,.2);padding:15px 36px;font-family:'Source Sans 3',sans-serif;font-size:14px;font-weight:500;letter-spacing:.5px;cursor:pointer;border-radius:2px;transition:border-color .25s,color .25s,transform .2s}
  .btn-ghost:hover{border-color:var(--green-lt);color:var(--green-lt);transform:translateY(-2px)}

  /* STATS */
  .stats-band{display:grid;grid-template-columns:repeat(6,1fr);border-top:1px solid var(--border);border-bottom:1px solid var(--border);background:rgba(21,33,24,.9);backdrop-filter:blur(10px)}
  .stat-cell{padding:44px 28px;text-align:center;border-right:1px solid var(--border);transition:background .3s;position:relative;overflow:hidden}
  .stat-cell:last-child{border-right:none}
  .stat-cell:hover{background:var(--gold-dim)}
  .stat-icon{font-size:24px;margin-bottom:14px;display:block}
  .stat-num{font-family:'Lora',serif;font-size:34px;font-weight:700;color:var(--gold);display:block;line-height:1;margin-bottom:10px;text-shadow:0 2px 16px rgba(212,168,67,.25)}
  .stat-label{font-size:10px;letter-spacing:2px;text-transform:uppercase;color:var(--muted);font-weight:600}

  /* GALLERY */
  .gallery-section{padding:120px 60px;max-width:1240px;margin:0 auto}
  .section-eyebrow{font-size:11px;letter-spacing:3px;text-transform:uppercase;color:var(--green-lt);font-weight:600;margin-bottom:18px}
  .section-title{font-family:'Lora',serif;font-size:clamp(32px,4.5vw,56px);font-weight:700;line-height:1.08;letter-spacing:-.5px;color:var(--text);margin-bottom:16px}
  .section-title em{font-style:italic;color:var(--gold)}
  .section-lead{font-size:16px;line-height:1.8;color:var(--muted);max-width:480px;margin-bottom:64px}

  .photo-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:3px}
  .photo-card{position:relative;overflow:hidden;background:var(--bg3);cursor:pointer}
  .photo-card:nth-child(1){grid-column:span 7;grid-row:span 2}
  .photo-card:nth-child(2){grid-column:span 5}
  .photo-card:nth-child(3){grid-column:span 5}
  .photo-card:nth-child(4){grid-column:span 6}
  .photo-card:nth-child(5){grid-column:span 6}

  .photo-card img{width:100%;height:100%;object-fit:cover;display:block;transition:transform .6s cubic-bezier(.22,1,.36,1),filter .4s;filter:brightness(.88) saturate(.9);min-height:260px}
  .photo-card:nth-child(1) img{min-height:520px}
  .photo-card:hover img{transform:scale(1.04);filter:brightness(.65) saturate(1.1)}

  .photo-overlay{position:absolute;inset:0;background:linear-gradient(to top,rgba(8,16,9,.92) 0%,transparent 55%);opacity:0;transition:opacity .4s;display:flex;flex-direction:column;justify-content:flex-end;padding:28px}
  .photo-card:hover .photo-overlay{opacity:1}
  .photo-card:nth-child(1) .photo-overlay{opacity:1}
  .photo-caption{font-family:'Lora',serif;font-size:15px;font-style:italic;color:var(--text);line-height:1.5;margin-bottom:6px}
  .photo-location{font-size:11px;letter-spacing:2px;text-transform:uppercase;color:var(--green-lt);font-weight:600}

  /* DIVIDER */
  .divider{height:1px;background:linear-gradient(to right,transparent,var(--border),transparent);margin:0 60px}

  /* STORIES */
  .stories-section{padding:120px 60px;max-width:1200px;margin:0 auto}
  .stories-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:2px;background:var(--border);border:1px solid var(--border);margin-top:64px}
  .story-card{background:var(--bg3);padding:52px 44px;position:relative;overflow:hidden;transition:background .35s}
  .story-card:hover{background:rgba(45,106,79,.18)}
  .story-card::before{content:'"';position:absolute;top:-10px;right:24px;font-family:'Lora',serif;font-size:120px;font-weight:700;color:rgba(212,168,67,.06);line-height:1;pointer-events:none;user-select:none}
  .story-quote{font-family:'Lora',serif;font-style:italic;font-size:17px;line-height:1.75;color:var(--text);margin-bottom:36px;position:relative;z-index:1}
  .story-quote::before{content:'';display:block;width:36px;height:2px;background:var(--gold);margin-bottom:20px}
  .story-author{display:flex;align-items:center;gap:14px}
  .story-avatar{width:44px;height:44px;border-radius:50%;background:linear-gradient(135deg,var(--green),rgba(212,168,67,.5));border:1px solid rgba(255,255,255,.15);display:flex;align-items:center;justify-content:center;font-size:18px;flex-shrink:0}
  .author-name{font-size:14px;font-weight:600;color:var(--text);letter-spacing:.2px}
  .author-role{font-size:12px;color:var(--muted);margin-top:3px;letter-spacing:.3px}

  /* TIMELINE */
  .timeline-section{padding:120px 60px;max-width:800px;margin:0 auto}
  .timeline{margin-top:64px;position:relative}
  .timeline::before{content:'';position:absolute;left:24px;top:0;bottom:0;width:1px;background:linear-gradient(to bottom,var(--gold),var(--green-lt),transparent)}
  .tl-item{display:flex;gap:36px;margin-bottom:56px;position:relative}
  .tl-dot{width:48px;height:48px;flex-shrink:0;border-radius:50%;background:var(--bg3);border:1px solid var(--border);display:flex;align-items:center;justify-content:center;font-size:20px;position:relative;z-index:1;transition:border-color .3s,background .3s}
  .tl-item:hover .tl-dot{border-color:var(--gold);background:var(--gold-dim)}
  .tl-body{padding-top:8px}
  .tl-label{font-size:11px;letter-spacing:2.5px;text-transform:uppercase;color:var(--green-lt);font-weight:600;margin-bottom:8px}
  .tl-title{font-family:'Lora',serif;font-size:19px;font-weight:600;color:var(--text);line-height:1.4;letter-spacing:-.2px;margin-bottom:10px}
  .tl-sub{font-size:14px;color:var(--muted);line-height:1.7}

  /* CTA BAND */
  .cta-band{background:linear-gradient(135deg,#1c3a2a 0%,#102518 50%,#1c3a2a 100%);border-top:1px solid var(--border);border-bottom:1px solid var(--border);padding:110px 60px;text-align:center;position:relative;overflow:hidden}
  .cta-band::before{content:'';position:absolute;inset:0;background:url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%232d6a4f' fill-opacity='0.1'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");opacity:.7}
  .cta-inner{position:relative;z-index:1;max-width:680px;margin:0 auto}
  .cta-eyebrow{font-size:11px;letter-spacing:3px;text-transform:uppercase;color:var(--green-lt);font-weight:600;margin-bottom:24px}
  .cta-title{font-family:'Lora',serif;font-size:clamp(32px,4.5vw,58px);font-weight:700;line-height:1.08;letter-spacing:-.5px;color:var(--text);margin-bottom:20px;text-shadow:0 2px 24px rgba(0,0,0,.5)}
  .cta-title em{font-style:italic;color:var(--gold)}
  .cta-desc{font-size:17px;color:var(--muted);line-height:1.8;margin-bottom:44px}

  /* FOOTER */
  .footer{border-top:1px solid var(--border);padding:36px 60px;display:flex;align-items:center;justify-content:space-between;position:relative;z-index:1}
  .footer-logo{font-family:'Lora',serif;font-size:18px;font-weight:600;color:var(--gold)}
  .footer-copy{font-size:12px;color:var(--muted);letter-spacing:.5px}

  /* REVEAL */
  .reveal{opacity:0;transform:translateY(28px);transition:opacity .7s,transform .7s}
  .reveal.visible{opacity:1;transform:translateY(0)}

  @keyframes fadeUp{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}
  @keyframes fadeIn{from{opacity:0}to{opacity:1}}

  ::-webkit-scrollbar{width:6px}
  ::-webkit-scrollbar-track{background:var(--bg)}
  ::-webkit-scrollbar-thumb{background:var(--border);border-radius:3px}

  @media(max-width:1024px){
    .stats-band{grid-template-columns:repeat(3,1fr)}
    .stat-cell:nth-child(3){border-right:none}
    .stories-grid{grid-template-columns:1fr}
    .photo-card:nth-child(1){grid-column:span 12}
    .photo-card:nth-child(2),.photo-card:nth-child(3){grid-column:span 6}
    .photo-card:nth-child(4),.photo-card:nth-child(5){grid-column:span 6}
  }
  @media(max-width:768px){
    .nav{padding:18px 24px}
    .gallery-section,.stories-section,.timeline-section{padding:80px 24px}
    .stats-band{grid-template-columns:repeat(2,1fr)}
    .stat-cell:nth-child(2n){border-right:none}
    .photo-grid{grid-template-columns:1fr}
    .photo-card{grid-column:span 1!important}
    .cta-band{padding:80px 24px}
    .footer{flex-direction:column;gap:10px;text-align:center;padding:28px 24px}
    .divider{margin:0 24px}
  }
`

/* ─── Particles ─── */
function ParticleCanvas() {
  const ref = useRef(null)
  useEffect(() => {
    const c = ref.current, ctx = c.getContext('2d')
    let W, H, pts, raf
    const resize = () => { W = c.width = innerWidth; H = c.height = innerHeight }
    const P = () => ({ x:Math.random()*innerWidth, y:Math.random()*innerHeight, r:Math.random()*2+.4, vx:(Math.random()-.5)*.18, vy:-Math.random()*.22-.06, a:Math.random()*.5+.1, h:Math.random()>.5?'#52b788':'#e8a838' })
    resize(); pts = Array.from({length:90},P); addEventListener('resize',resize)
    const loop = () => {
      ctx.clearRect(0,0,W,H)
      pts.forEach(p => {
        p.x+=p.vx; p.y+=p.vy
        if(p.y<-10){p.y=H+10;p.x=Math.random()*W}
        if(p.x<-10) p.x=W+10; if(p.x>W+10) p.x=-10
        ctx.beginPath(); ctx.arc(p.x,p.y,p.r,0,Math.PI*2)
        ctx.fillStyle=p.h; ctx.globalAlpha=p.a; ctx.fill()
      })
      raf=requestAnimationFrame(loop)
    }
    loop()
    return () => { cancelAnimationFrame(raf); removeEventListener('resize',resize) }
  }, [])
  return <canvas id="particle-canvas" ref={ref} />
}

/* ─── Scroll reveal ─── */
function useReveal() {
  useEffect(() => {
    const els = document.querySelectorAll('.reveal')
    const io = new IntersectionObserver(entries => {
      entries.forEach(e => { if(e.isIntersecting){ e.target.classList.add('visible'); io.unobserve(e.target) } })
    }, { threshold: 0.12 })
    els.forEach(el => io.observe(el))
    return () => io.disconnect()
  }, [])
}

/* ═══════════════════════════════════════════════════ */
export default function ImpactPage() {
  const nav = useNavigate()
  useReveal()

  return (
    <>
      <style>{STYLES}</style>
      <ParticleCanvas />

      {/* NAV */}
      <nav className="nav">
        <div className="nav-logo" onClick={() => nav('/')}>Food<span>Bridge</span></div>
        <button className="nav-back" onClick={() => nav('/')}>
          <span className="nav-back-arr">←</span> Back to Home
        </button>
      </nav>

      <div className="page">

        {/* ── HERO ── */}
        <section className="hero">
          <div className="hero-tag"><span className="tag-dot"/>Real Stories · Verified Impact</div>
          <h1 className="hero-title">Meals that<br/><em>changed</em><br/>lives.</h1>
          <div className="hero-line"/>
          <p className="hero-desc">
            Behind every number is a face, a family, a moment of relief.
            This is the story of what happens when surplus meets need.
          </p>
          <div className="hero-btns">
            <button className="btn-primary" onClick={() => nav('/')}>🍲 Make a Donation</button>
            <button className="btn-ghost"   onClick={() => nav('/donations')}>💛 View Active Needs</button>
          </div>
        </section>

        {/* ── STATS ── */}
        <div className="stats-band">
          {STATS.map((s,i) => (
            <div className="stat-cell reveal" key={s.label} style={{transitionDelay:`${i*.08}s`}}>
              <span className="stat-icon">{s.icon}</span>
              <span className="stat-num">{s.num}</span>
              <span className="stat-label">{s.label}</span>
            </div>
          ))}
        </div>

        {/* ── GALLERY ── */}
        <div className="gallery-section">
          <p className="section-eyebrow reveal">📸 On the Ground</p>
          <h2 className="section-title reveal">Faces of <em>impact</em></h2>
          <p className="section-lead reveal">
            Photographs from our distribution drives and NGO partner sites across South Asia.
          </p>
          <div className="photo-grid">
            {(IMG_SRCS.length ? IMG_SRCS : UPLOADED).map((src, i) => (
              <div className="photo-card reveal" key={i} style={{transitionDelay:`${i*.1}s`}}>
                <img src={src} alt={IMPACT_DATA[i].caption} loading={i===0?'eager':'lazy'} />
                <div className="photo-overlay">
                  <p className="photo-caption">{IMPACT_DATA[i].caption}</p>
                  <span className="photo-location">📍 {IMPACT_DATA[i].location}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="divider"/>

        {/* ── STORIES ── */}
        <div className="stories-section">
          <p className="section-eyebrow reveal">💬 Voices from the Field</p>
          <h2 className="section-title reveal">What people <em>say</em></h2>
          <p className="section-lead reveal">From donors to NGO directors to beneficiaries — hear the stories behind the meals.</p>
          <div className="stories-grid">
            {STORIES.map((s,i) => (
              <div className="story-card reveal" key={i} style={{transitionDelay:`${i*.12}s`}}>
                <p className="story-quote">{s.quote}</p>
                <div className="story-author">
                  <div className="story-avatar">{s.emoji}</div>
                  <div>
                    <div className="author-name">{s.name}</div>
                    <div className="author-role">{s.role}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="divider"/>

        {/* ── TIMELINE ── */}
        <div className="timeline-section">
          <p className="section-eyebrow reveal">🌱 Our Journey</p>
          <h2 className="section-title reveal">How we <em>grew</em></h2>
          <p className="section-lead reveal">From a single city pilot to a network spanning South Asia — built meal by meal.</p>
          <div className="timeline">
            {TIMELINE.map((t,i) => (
              <div className="tl-item reveal" key={i} style={{transitionDelay:`${i*.15}s`}}>
                <div className="tl-dot">{t.icon}</div>
                <div className="tl-body">
                  <p className="tl-label">{t.label}</p>
                  <p className="tl-title">{t.title}</p>
                  <p className="tl-sub">{t.sub}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* ── CTA ── */}
        <div className="cta-band">
          <div className="cta-inner">
            <p className="cta-eyebrow">🌾 Join the Movement</p>
            <h2 className="cta-title">Be the reason<br/>someone eats <em>tonight.</em></h2>
            <p className="cta-desc">Every surplus meal you donate reaches a verified NGO partner within minutes. Setup takes two minutes. The impact lasts a lifetime.</p>
            <div className="hero-btns">
              <button className="btn-primary" onClick={() => nav('/')}>🍲 Donate Food Now</button>
              <button className="btn-ghost"   onClick={() => nav('/donations')}>View NGO Needs</button>
            </div>
          </div>
        </div>

        {/* ── FOOTER ── */}
        <footer className="footer">
          <div className="footer-logo">FoodBridge</div>
          <div className="footer-copy">© 2026 · Fighting hunger, one meal at a time.</div>
        </footer>

      </div>
    </>
  )
}